In [1]:
import tensorflow as tf
import numpy as np
from PIL import Image
sess = tf.Session()

In [2]:
sess= tf.Session()

In [1]:
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets('MNIST_data',one_hot=True)

Extracting MNIST_data\train-images-idx3-ubyte.gz
Extracting MNIST_data\train-labels-idx1-ubyte.gz
Extracting MNIST_data\t10k-images-idx3-ubyte.gz
Extracting MNIST_data\t10k-labels-idx1-ubyte.gz


In [6]:
batch = mnist.train.next_batch(50)
batch[0]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [4]:
width = 28
height = 28
flat = width*height
class_output = 10

In [5]:
x=tf.placeholder(tf.float32,shape=[None,flat])
y_=tf.placeholder(tf.float32,shape=[None,class_output])

In [6]:
def weight_variable(shape):
    initial = tf.truncated_normal(shape,stddev=0.1)
    return(tf.Variable(initial))

In [7]:
def bias_variable(shape):
    initial= tf.constant(0.1,shape = shape)
    return tf.Variable(initial)
    

In [8]:
def conv2d(x,W):
    return tf.nn.conv2d(x,W,strides=[1,1,1,1],padding='SAME')

In [9]:
def max_pool_2x2(x):
    return tf.nn.max_pool(x,ksize=[1,2,2,1],strides=[1,2,2,1],padding='SAME')

In [10]:
W_conv1=weight_variable([5,5,1,32])
b_conv1=bias_variable([32])

In [11]:
x_image = tf.reshape(x,[-1,28,28,1])

In [12]:
convolve1 = conv2d(x_image,W_conv1)+b_conv1

In [13]:
h_conv1=tf.nn.relu(convolve1)

In [14]:
h_pool1 = max_pool_2x2(h_conv1)

In [15]:
layer1 = h_pool1

In [16]:
W_conv2=weight_variable([5,5,32,64])
b_conv2=bias_variable([64])

In [17]:
convolve2 = conv2d(layer1,W_conv2)+b_conv2

In [18]:
h_conv2=tf.nn.relu(convolve2)

In [19]:
h_pool2 = max_pool_2x2(h_conv2)

In [20]:
layer2 = h_pool2

In [21]:
W_fc1 = weight_variable([7*7*64,1024])
b_fc1 = bias_variable([1024])

In [22]:
layer2_matrix = tf.reshape(layer2,[-1,7*7*64])

In [23]:
matmul_fc1=tf.matmul(layer2_matrix,W_fc1)+b_fc1

In [24]:
h_fc1 = tf.nn.relu(matmul_fc1)

In [25]:
layer3 = h_fc1

In [26]:
keep_prob=tf.placeholder(tf.float32)
layer3_drop= tf.nn.dropout(layer3,keep_prob)

In [27]:
W_fc2 = weight_variable([1024,10])
b_fc2 = bias_variable([10])

In [28]:
matmul_fc2=tf.matmul(layer3_drop,W_fc2)+b_fc2

In [29]:
y_conv = tf.nn.softmax(matmul_fc2)

In [30]:
layer4 = y_conv

In [31]:
cross_entropy = tf.reduce_mean(-tf.reduce_sum(y_*tf.log(layer4),reduction_indices=[1]))

In [32]:
train_step=tf.train.AdamOptimizer(1e-4).minimize(cross_entropy)

In [33]:
correct_prediction = tf.equal(tf.argmax(layer4,1),tf.argmax(y_,1))

In [34]:
accuracy = tf.reduce_mean(tf.cast(correct_prediction,tf.float32))

In [35]:
sess.run(tf.global_variables_initializer())

In [36]:
W_conv1.shape

TensorShape([Dimension(5), Dimension(5), Dimension(1), Dimension(32)])

In [37]:
convolve2.shape

TensorShape([Dimension(None), Dimension(14), Dimension(14), Dimension(64)])

In [40]:
for i in range(200):
    batch = mnist.train.next_batch(50)
    if i%100 ==0:
        train_accuracy= sess.run (accuracy,feed_dict={x:batch[0],y_:batch[1],keep_prob:1.0})
        print('step %d,training accuracy %g'%(i,float(train_accuracy)))
    sess.run(train_step,feed_dict={x:batch[0],y_:batch[1],keep_prob:0.5})

step 0,training accuracy 0.26
step 100,training accuracy 0.9


In [38]:
sess.run(W_conv1)

array([[[[ 0.07775881, -0.02708309, -0.00261355,  0.16374186,
          -0.04172755,  0.0357428 , -0.03539734,  0.09974255,
           0.05167831, -0.03482849,  0.07484945,  0.10015215,
           0.04556036, -0.03900407, -0.07141849, -0.15257356,
           0.12799563, -0.09625448, -0.00449123,  0.01878783,
           0.04768424, -0.12370061, -0.07829511,  0.14381798,
          -0.00230434, -0.04122631,  0.08702505,  0.08773912,
           0.03054208, -0.00188253,  0.0736255 , -0.1786683 ]],

        [[ 0.13816087,  0.07591433,  0.01693912, -0.06169013,
          -0.04370298,  0.0315219 , -0.10507732,  0.00169128,
          -0.11752122, -0.13542777,  0.19318603,  0.15163678,
           0.09319669,  0.08324329, -0.13817981,  0.04851867,
          -0.1698478 , -0.01698303, -0.0334915 ,  0.14768869,
           0.07061774, -0.04673352,  0.03124901,  0.07542038,
           0.12898554, -0.04152853,  0.0308358 , -0.06004105,
           0.09173705,  0.07236038, -0.05982402, -0.0075782 ]],

  

In [41]:
sess.run(W_conv1)

array([[[[ 8.22333172e-02, -2.83065159e-02, -8.72170925e-03,
           1.66398838e-01, -4.57563996e-02,  3.49164903e-02,
          -3.63093764e-02,  9.55927745e-02,  4.99383658e-02,
          -3.79883163e-02,  6.86741099e-02,  1.01966485e-01,
           4.23225909e-02, -3.78920361e-02, -6.89595193e-02,
          -1.56818852e-01,  1.27683848e-01, -9.66216177e-02,
          -8.63305572e-03,  1.35606341e-02,  4.80879135e-02,
          -1.27212644e-01, -7.97469914e-02,  1.38878897e-01,
          -4.85199783e-03, -3.82836238e-02,  8.85466561e-02,
           8.65248442e-02,  2.91696135e-02, -6.05748082e-03,
           6.96978047e-02, -1.83111340e-01]],

        [[ 1.40054464e-01,  7.44254440e-02,  1.16743539e-02,
          -5.92181273e-02, -4.70822304e-02,  2.96525825e-02,
          -1.07335381e-01, -1.60370069e-03, -1.19538739e-01,
          -1.36795789e-01,  1.87065557e-01,  1.51994392e-01,
           9.12702680e-02,  8.65143910e-02, -1.35356292e-01,
           4.48184423e-02, -1.70487761

In [39]:
sess.run(W_conv2)

array([[[[-0.04469685,  0.02712228, -0.08241566, ...,  0.00486321,
           0.07670782,  0.08957876],
         [-0.01560838, -0.1370622 , -0.00266672, ..., -0.08773642,
           0.16653387, -0.00272648],
         [-0.10398485, -0.1238421 , -0.05140356, ..., -0.07264312,
          -0.00261033, -0.1755191 ],
         ...,
         [ 0.08242568, -0.18997718,  0.01229636, ...,  0.0162913 ,
           0.02844909, -0.07387951],
         [ 0.07492224,  0.16531892, -0.0092263 , ...,  0.12445145,
          -0.09445268, -0.09267218],
         [ 0.01872968,  0.09966613, -0.07842221, ..., -0.10898923,
           0.0633409 ,  0.11828213]],

        [[ 0.04814429,  0.15906638, -0.02884609, ...,  0.12787108,
           0.02938312,  0.04113036],
         [ 0.12686011,  0.02969731,  0.00957086, ..., -0.06944176,
           0.00031767, -0.05940044],
         [ 0.00880645, -0.03428664, -0.06546956, ..., -0.09342858,
           0.02450452,  0.11547489],
         ...,
         [-0.05341141, -0.05783653

In [42]:
sess.run(W_conv2)

array([[[[-4.47984375e-02,  3.01507507e-02, -8.47680569e-02, ...,
           3.30589106e-03,  8.05812404e-02,  8.98494199e-02],
         [-1.50244292e-02, -1.35428846e-01, -4.66513075e-03, ...,
          -9.02251229e-02,  1.65826336e-01, -1.87562674e-03],
         [-1.05677582e-01, -1.26234442e-01, -5.15662730e-02, ...,
          -7.47632384e-02, -8.88212025e-03, -1.77471906e-01],
         ...,
         [ 8.08076337e-02, -1.92362145e-01,  1.17376596e-02, ...,
           1.58409066e-02,  2.80910525e-02, -7.47140795e-02],
         [ 7.42632449e-02,  1.64549679e-01, -1.10691106e-02, ...,
           1.22811183e-01, -9.16485190e-02, -9.34871808e-02],
         [ 1.63594186e-02,  9.75993797e-02, -8.08506161e-02, ...,
          -1.11071207e-01,  6.67579621e-02,  1.18694536e-01]],

        [[ 4.97630090e-02,  1.61542282e-01, -3.15532908e-02, ...,
           1.26989201e-01,  3.22465710e-02,  4.00049947e-02],
         [ 1.26684681e-01,  3.22842337e-02,  6.34114351e-03, ...,
          -7.30497688e

In [44]:
sess.run(b_conv1)

array([0.09635654, 0.10166499, 0.09655527, 0.10467564, 0.09686988,
       0.10266598, 0.09862279, 0.09534354, 0.09874947, 0.10086881,
       0.09633119, 0.10067867, 0.09649763, 0.10375625, 0.09934362,
       0.09394867, 0.09492451, 0.09497171, 0.09413431, 0.09527262,
       0.10144595, 0.09600618, 0.09706385, 0.09542526, 0.09506104,
       0.09577426, 0.09956685, 0.10297439, 0.09516665, 0.1004603 ,
       0.09527412, 0.09651845], dtype=float32)

In [62]:
ccy = tf.constant(aa,[5,5])

TypeError: unhashable type: 'list'

In [59]:
sess.run(tf.global_variables_initializer())
sess.run(ccy)

array([[[[ 0.01820642]],

        [[-0.01502777]],

        [[-0.1274337 ]],

        [[ 0.00548361]],

        [[-0.06110265]]],


       [[[-0.08502398]],

        [[-0.0724655 ]],

        [[-0.12623124]],

        [[-0.00944287]],

        [[-0.07724746]]],


       [[[-0.14342186]],

        [[-0.11842691]],

        [[-0.04523838]],

        [[ 0.17140739]],

        [[-0.1650614 ]]],


       [[[-0.09886407]],

        [[-0.05657091]],

        [[ 0.02891127]],

        [[-0.10202297]],

        [[ 0.04159883]]],


       [[[ 0.07476608]],

        [[-0.12108735]],

        [[-0.05962312]],

        [[ 0.08296469]],

        [[ 0.15466458]]]], dtype=float32)

In [88]:
aa = np.array(range(5*5*4*2))

SyntaxError: unexpected EOF while parsing (<ipython-input-88-66524308f0bc>, line 1)

In [89]:
aa.reshape([5,5,2,4])

ValueError: cannot reshape array of size 100 into shape (5,5,2,4)