In [1]:
import tensorflow as tf
import sys


In [2]:
train = [
    ([0.0, 0.0, 0.0], 0.0),
    ([0.0, 0.0, 1.0], 1.0),
    ([0.0, 1.0, 0.0], 0.0),
    ([0.0, 1.0, 1.0], 0.0),
    ([1.0, 0.0, 0.0], 1.0),
    ([1.0, 0.0, 1.0], 1.0),
    ([1.0, 1.0, 0.0], 0.0),
    ([1.0, 1.0, 1.0], 0.0),
   
    
    
]

In [3]:
sess = tf.Session()
epoch = 20000


w = tf.get_variable("my_variable", [2,3], dtype=tf.float32, initializer=tf.glorot_uniform_initializer(
    seed=None,
    dtype=tf.float32
))



w_2 = tf.get_variable("my_variable_2", [1,2], dtype=tf.float32, initializer=tf.glorot_uniform_initializer(
    seed=None,
    dtype=tf.float32
))

sess.run (tf.global_variables_initializer())




    




        
    


In [6]:

for inputs, correct in train:
    
    x = tf.constant(inputs ,name='input' )
    y_ = tf.constant (correct, name='correct_answer')
    y = tf.reduce_sum(tf.multiply(w, x),axis=1)
    itog_hiden = tf.sigmoid(y)
        
        
    itog_output = tf.reduce_sum(tf.multiply(w_2,itog_hiden))
    predict = tf.sigmoid(itog_output)
    loss = tf.pow(predict - y_,2)
    
    step = tf.train.GradientDescentOptimizer(0.1).minimize(loss)
    for i in range (epoch): 
          
        sess.run (step)
        


        
    
        
    
    
    

In [9]:
for inputs, correct in train:
    
    x = tf.constant(inputs ,name='input' )

        
    y = tf.reduce_sum(tf.multiply(w, x),axis=1)
    itog_hiden = tf.sigmoid(y)
        
        
    itog_output = tf.reduce_sum(tf.multiply(w_2,itog_hiden))
    predict = tf.sigmoid(itog_output)
    print ('for inputs {} expented : {} actual {}'.format (inputs,sess.run(predict),correct))

for inputs [0.0, 0.0, 0.0] expented : 0.07393669337034225 actual 0.0
for inputs [0.0, 0.0, 1.0] expented : 0.45958855748176575 actual 1.0
for inputs [0.0, 1.0, 0.0] expented : 0.0004719749849755317 actual 0.0
for inputs [0.0, 1.0, 1.0] expented : 0.00037141572101972997 actual 0.0
for inputs [1.0, 0.0, 0.0] expented : 0.9054892063140869 actual 1.0
for inputs [1.0, 0.0, 1.0] expented : 0.8863926529884338 actual 1.0
for inputs [1.0, 1.0, 0.0] expented : 0.0049822647124528885 actual 0.0
for inputs [1.0, 1.0, 1.0] expented : 0.0037833002861589193 actual 0.0


In [7]:
print (sess.run(w))

[[-2.270081   6.877352  -3.2895944]
 [ 3.8544967 -1.7040707 -3.1198711]]


In [8]:
print (sess.run(w_2))

[[-8.141552   3.0860856]]
